#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

cd "${BASH_SOURCE%/*}"

gen() {
  mkdir -p .tmp/
  ls -al .tmp
  jsonnet -J ../../ --multi .tmp/ all.jsonnet
}

deploy() {
  gen

  # validate the config
  # TODO: auto fix the storage account
  
  # Workaround: https://github.com/hashicorp/terraform/issues/7153
  terraform apply -state=./.tmp/terraform.tfstate .tmp || true
  
  # TODO: this dumps tfstate into ./azure/ rather than ./azure/.tmp/
  terraform apply -state=./.tmp/terraform.tfstate .tmp

  while ! validate; do
    sleep 5
    export KUBECONFIG="$(pwd)/.tmp/kubeconfig.json"
    kubectl get nodes
  done
}


validate() {
  true
}

destroy() {
  if [[ "${FORCE_DESTROY}" == "y" ]]; then
    teraform destroy .tmp -force
  else
    terraform destroy .tmp
  fi
}

case "${1:-}" in
  "")
    ;;
  "deploy")
    deploy
    ;;
  "destroy")
    destroy
    ;;
  "gen")
    gen
    ;;
esac
