#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

cd "${BASH_SOURCE%/*}"

gen() {
  mkdir -p .tmp/
  ls -al .tmp
  jsonnet -J ../../ --multi .tmp/ all.jsonnet
}

deploy() {
  gen

  # validate the config
  # TODO: auto fix the storage account
  
  # Workaround: https://github.com/hashicorp/terraform/issues/7153
  terraform apply -state=./.tmp/terraform.tfstate .tmp || true
  
  # TODO: this dumps tfstate into ./azure/ rather than ./azure/.tmp/
  terraform apply -state=./.tmp/terraform.tfstate .tmp

  ls -al ./.tmp/
  num_nodes="$(cat ./../../.config.json | jq -r '.phase1.num_nodes')"

  while true; do
    sleep 5
    export KUBECONFIG="$(pwd)/.tmp/kubeconfig.json"
    hcount=$(kubectl get nodes | grep 'Ready' | wc -l)
    if [[ "${hcount}" -lt "${num_nodes}" ]]; then
      echo "healthy nodes: wanted: ${node_count} actual:${hcount}"
      return -1
    else
      return
    fi
  done
}


validate() {
  true
}

destroy() {
  if [[ "${FORCE_DESTROY}" == "y" ]]; then
    terraform destroy -state=./.tmp/terraform.tfstate -force .tmp
  else
    terraform destroy -state=./.tmp/terraform.tfstate .tmp
  fi
}

case "${1:-}" in
  "")
    ;;
  "deploy")
    deploy
    ;;
  "destroy")
    destroy
    ;;
  "gen")
    gen
    ;;
esac
