#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

gen() {
	cd "${BASH_SOURCE%/*}"
	mkdir -p .tmp/
	jsonnet --multi .tmp/ --tla-code-file cfg=../.config.json all.jsonnet
}

deploy() {
	gen
	mkdir -p /tmp/kubectl/schema
	kubectl apply --schema-cache-directory=/tmp/kubectl/schema; -f ./.tmp/
}

case "${1:-}" in
  "")
    ;;
  "deploy")
    deploy
    ;;
  "gen")
    gen
    ;;
esac
